project:
  type: website

website:
  title: "Courses, Tutorials and Slides"
  navbar:
    title: Bioinformatic Course
    search: true
    left:
      - href: index.qmd
        text: Home

  page-footer: 
    right:
      - text: '<p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial 4.0 International License</a>.</p>'
    border: true
    background: "#f8f9fa"
        
format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    toc: true

editor: visual

execute: 
  freeze: auto
